### ISSUE TITLE
I'd like to integrate a weather reporting smart function using Open Weather API

### ISSUE THREAD

**Issue by wheatbrad** [andrewwcaldwell/ChatFaces#11]
When a user asks via Howler 'What's the weather like?' the app will respond with the current weather utilizing data returned from the [Open Weather API](http://openweathermap.org/api). 

I'm leaning toward making **weather** the keyword that initiates the display of local weather. We are not including a location finding API so if a location is not specified then our smart weather function will display the weather for Charlotte, NC.

Ex. _"What's the **weather** like today?"_
`return weather for Charlotte`

To address the idea of location based weather reporting maybe we assign/look-for the keyword **for**, and **in** in the string, the next word would be our location argument.

Ex. _"What's the **weather** like **in** **San Francisco**?"_
Ex. _"What's today's **weather** **for** **San Francisco** California?"_
`return weather for San Francisco`

**Comment by andrewwcaldwell** [comment]
That seems fine. The same logic that initiates reading the message text
content can be used for the addition of <a>links so we definitely should
focus on that

On Thursday, March 24, 2016, Brad Runnels notifications@github.com wrote:

> When a user asks via Howler 'What's the _weather_ like?' the app will
> respond with the current weather utilizing data returned from the Open
> Weather API http://openweathermap.org/api.
> 
> I'm leaning toward making _weather_ the keyword that initiates the
> display of local weather. We are not including a location finding API so if
> a location is not specified then our smart weather function will display
> the weather for Charlotte, NC.
> 
> To address the idea of location based weather reporting maybe we
> assign/look-for the keyword _for_ in the string, the next word would be
> our location argument.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/andrewwcaldwell/ChatFaces/issues/11

## 

My phone did this...

**Comment by andrewwcaldwell** [comment]
Merge of PR #19 closes weather
