### ISSUE TITLE
Add Link recognition, embed <a> into Messages

### ISSUE THREAD

**Issue by andrewwcaldwell** [andrewwcaldwell/ChatFaces#12]
Will need to create some javascript to recognize links in message body and append an <a> tag into message content to that will link to that site.

`<a href="URL" target="_blank">TEXTCONTENT</a>`
Use THING.href to set url and THING.target _blank to launch from new tab.

**Comment by wheatbrad** [comment]
I'm about to have this issue complete - _hope you weren't working on this task!_  If you were... my bad for not communicating this to you.

**Comment by andrewwcaldwell** [comment]
I had some things I was messing with but if you think you got it get it done and installed. I'll see if i can make heads or tails of that and attempt emojis.. definitely want all the work/practice i can get.

**Comment by andrewwcaldwell** [comment]
this one is closed and tested via PR #18
