### ISSUE TITLE
Run Gulp and Browserify

### ISSUE THREAD

**Issue by andrewwcaldwell** [andrewwcaldwell/ChatFaces#13]
Need to go ahead and run our code through and set public folder to make sure app is working before adding next set of javascript functions.

**Comment by wheatbrad** [comment]
**brad-gulp** PR #14 will satisfy this issue once properly merged

**Comment by andrewwcaldwell** [comment]
OK PR #14 covered this issue. Closing it now. Good work @wheatbrad
