### ISSUE TITLE
Set Interval leaves no Need for Refresh Button.

### ISSUE THREAD

**Issue by andrewwcaldwell** [andrewwcaldwell/ChatFaces#2]
Howler relies on user to click refresh for posting and refreshing the individual chat messages. I would rather use Chit-Chat's interval refresh and updating on the send button listener. Its smoother.
Brad, I'm not sure how you did that work exactly? Does the send button listener have both a Post and Get feature or is it entirely on the interval refresh?

**Comment by wheatbrad** [comment]
Chit-Chat's GET request is wrapped in a function called retrieveChat() that fires once on page load and then at 5 second intervals. I makes calls to the server at said interval but will not write data to the chat view unless there is something new to write. It does this by making comparisons on the length of the JSON string.

**Comment by andrewwcaldwell** [comment]
Ok. thats pretty smooth. Have you brought your JS onto the main branch yet?

**Comment by wheatbrad** [comment]
I just initiated PR #4 to merge the js branch with all those goodies into the main branch. Yay
