### ISSUE TITLE
CSS changes to Drop Refresh Button

### ISSUE THREAD

**Issue by andrewwcaldwell** [andrewwcaldwell/ChatFaces#3]
Our base CSS from Howler has a refresh button that is in the upper area. That button will be unnecessary. It is currently styled to share a percentage of space horizontally with two other elements:
Tell Us Your Name? and Username Input Field.  

I suggest:
1) Update Tell us your name to be fixed width (auto?) as the left most element in row.
2) Update Username Input field to 100% of remaining width..(parent container has a determined width so it should work to literally make width:100%;  display: Inline-block; for both..

**Comment by wheatbrad** [comment]
Absolutely! It's a certainty that we will not be needing the refresh button.

**Comment by wheatbrad** [comment]
Resolved with css-edits merge!
