### ISSUE TITLE
Integrating Random User Generator into ChatFaces

### ISSUE THREAD

**Issue by wheatbrad** [andrewwcaldwell/ChatFaces#5]
- need to identify the html elements we want to insert 'random user' data into and then append those element into the chat view. 
- need to create styles for these elements.
- need to incorporate the javascript that facilitates the data from RUG into our js structure

**Comment by andrewwcaldwell** [comment]
Have made a new branch (local to me) to work this into app.js (module and require randomUser.js).

**Comment by andrewwcaldwell** [comment]
recent pull request #20 closes.
