### ISSUE TITLE
Var for JSON.parse data differs in the merge.

### ISSUE THREAD

**Issue by andrewwcaldwell** [andrewwcaldwell/ChatFaces#6]
Just spotted this one. Our code is using different vars for this.
Mine is "echo" yours is "data"
will need to change all instances of var echo to data.

**Comment by wheatbrad** [comment]
@andrewwcaldwell → alrighty I'll get on it

**Comment by wheatbrad** [comment]
technically this issue has been resolved so I'm closing and will open a new issue to address the inclusion of the time stamp and random user js

-- actually, i've already opened 2 issues #8, #5 for zee above
